= Backend Installation

To start using mobile specific features such as Synchronization, you must install the backend components. If you already have a running instance of the Python Web App, Sync Gateway and Couchbase Server you can skip this section of the tutorial.

There are three alternative options available to install those components.

[cols="1,1,1"]
|===
| xref:tutorials:mobile-travel-sample:installation/manual.adoc[Manual]
| xref:tutorials:mobile-travel-sample:installation/docker.adoc[Docker (Local)]
| xref:tutorials:mobile-travel-sample:installation/cloud.adoc[Cloud (RightScale)]

| Here, you would download and install the components on your local machine.
| In this case, you would install all the server components in separate docker containers on your local machine.
| In this case, you can launch and connect to an instance of the server components running on a cloud instance.
|===

NOTE: Make sure to use the same installation option for _all_ server components (i.e. if you selected Docker (Local), then you must use docker for all of them and so on.)
