try-cb-python:
    image: jamiltz/try-cb-python 
    ports:
        - 8080:8080
    container_name: try_cb_python

sync-gateway:
    image: connectsv/sync-gateway-internal:1.5.0-community 
    ports:
        - "4984-4985:4984-4985"
    command: -adminInterface :4985 /etc/sync_gateway/sync_gateway.json
    volumes:
        - ${PWD}/sync-gateway-config-travelsample.json:/etc/sync_gateway/sync_gateway.json
    container_name: sync_gateway
