try-cb-python:
    image: connectsv/try-cb-python:7.1.1-server
    ports:
        - 8080:8080
    container_name: cb-backend-py

sync-gateway:
    image: couchbase/sync-gateway:3.0.4-enterprise
    ports:
        - "4984-4986:4984-4986"
    command: -adminInterface :4985 /etc/sync_gateway/config.json
    volumes:
        - ${PWD}/sync-gateway-config-travelsample-docker.json:/etc/sync_gateway/config.json
    container_name: sync_gateway
