= Travel Sample Mobile App
//:page-aliases: tutorials:travel-sample:develop/swift,tutorials:travel-sample:develop/swift/index

== Pre-requisites

* Xcode 10.1+: downloadable latest version from the https://itunes.apple.com/us/app/xcode/id497799835?mt=12[Mac App Store].

== Getting Started

* Clone the "master" branch of the Travel Sample app from GitHub. We are doing a shallow pull with `depth` as 1 to speed the cloning process. 
+
[source,bash]
----
git clone -b master --depth 1 https://github.com/couchbaselabs/mobile-travel-sample.git
----
+
If you are building using Xcode 10.1, you will have to download the Swift 4.2 compatible version of Couchbase Lite framework
* In Terminal, navigate to the *TravelSample* directory.
+
[source,bash]
----
cd /path/to/mobile-travel-sample/ios/TravelSample
----
* Run the following script to download and install Couchbase Lite.
A script is provided for different versions of Xcode and Swift.
+
[{tabs}]
====
Xcode 10::
+
--
[source,bash]
----
sh install_10.sh
----
--
====
* Open the `TravelSample.xcodeproj` using Xcode
* Build and run the project using simulator
* Verify that the login screen appears in the simulator 
