= Backend Installation

First, we will install the "backend components" required for the tutorial.
This includes Couchbase Server, Sync Gateway and Python web app - essentially all components with the exception of the Couchbase Lite app.

If you already have a running instance of the Python Travel Sample Web App, Sync Gateway and Couchbase Server you can skip this section of the tutorial and proceed to the installation of the Couchbase Lite client app.

There are three options available to install those components.

[cols="1,1,1"]
|===
a| xref:{param-module}/installation/manual.adoc[Manual]
a| xref:{param-module}/installation/docker.adoc[Docker (Local)]
a| xref:{param-module}/installation/cloud.adoc[Cloud (RightScale)]

| Here, you would download and install the components on your local machine.
| In this case, you would install all the backend components in separate docker containers on your local machine.
| In this case, you can launch and connect to an instance of the backend components running on a cloud instance.
|===

NOTE: Make sure to use the same installation option for _all_ backend components, so if you select Docker (Local), then you must use docker for Python Travel Sample Web App, Sync Gateway and Couchbase Server.
